<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VASANTHA" name="test.SampleTest.DataProviderExample" tests="2" failures="0" timestamp="3 Jul 2011 16:06:08 GMT" time="17.406" errors="1">
  <testcase name="testDataProviderExample" time="3.922" classname="test.SampleTest.DataProviderExample">
    <error type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Element xpath=/descendant::a[text()=&#039;Kung fu Panda 2&#039;] not found">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element xpath=/descendant::a[text()='Kung fu Panda 2'] not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:97)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:91)
	at com.thoughtworks.selenium.DefaultSelenium.click(DefaultSelenium.java:167)
	at test.SampleTest.DataProviderExample.testDataProviderExample(DataProviderExample.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:995)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:920)
	at org.testng.TestNG.run(TestNG.java:856)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:72)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:82)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:133)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:105)
]]>
    </error>
  </testcase>
  <testcase name="testDataProviderExample" time="13.484" classname="test.SampleTest.DataProviderExample"/>
</testsuite>
